### PR TITLE
Virtual Player 2 Lightgun Support

### PR DESCRIPTION
**Pull request by iequalshane**

### CODE REVIEW

**Comment by iequalshane** [comment]
I have some concerns about how controllers are assigned here. Should I show a warning when controllers are double or triple assigned? Maybe the Gun1 should be restricted to either Joy2 when joy swap is not enabled or Joy1 when it is, and Gun2 is always Joy3?

**Comment by iequalshane** [comment]
One thing I wanted to do was allow a player to assign both guns to the same Joypad and if it was something like an Xbox 360 controller use a different analog stick and trigger for each gun in a sort of "akimbo" mode, but currently it's not possible to map 2 analog sticks from the same controller so I abandoned this idea for now.

**Comment by sorgelig** [comment]
is it just for one game?

**Comment by iequalshane** [comment]
Two games. Lethal Enforcers and Lethal Enforcers II.

**Comment by iequalshane** [comment]
While there are only 2 games with 2 lightguns on the Genesis/MegaCD, there's 1 on SNES, 1 on SMS. Eventually, there will be more for arcade cores. So I think it has some value if it doesn't complicate the OSD too much.

**Comment by iequalshane** [comment]
I have an idea where I can remove this option entirely and still make this work. I'll commit an update tonight.

**Comment by iequalshane** [comment]
Well, I wasn't able to remove the option entirely, but here's an idea for simpler settings where the joy assignments shouldn't conflict. I'd argue maybe even if we don't merge the 2 lightguns change, maybe a change where the single lightgun setting is reduced to "disabled,joy,mouse" where it's always assigned to the opposite joypad as the first player is potentially useful.

**Comment by sorgelig** [comment]
Lightgun is quite niche device. Although it's nice to have lightgun support, exaggerating it to 2 lightguns and cluttered OSD i think is not a good idea.. I'm afraid if some bug in input will be discovered, it will be hard to find.. I don't know.. Need to think...

**Comment by iequalshane** [comment]
That's understandable. If need be, I can shelve this change until we think it has more value. Maybe in the future, if we have some way to more easily define gun-type devices in the main settings this can be simplified.

**Pull request closed without merging**
