### PR TITLE
Jotego's Old TV Filter

### PR DESCRIPTION
**Pull request by drstorm**
The Old TV filter does not replace the existing Composite Blend.

Filter code: https://github.com/jotego/jtframe

### CODE REVIEW

**Comment by Crtlovergaddem** [comment]
great job I would like to ask you if you could pass the function of horizontal and vertical scrolling of the game cores

**Comment by birdybro** [comment]
> 
> 
> great job I would like to ask you if you could pass the function of horizontal and vertical scrolling of the game cores

You mean moving the position of the screen on a CRT? This is not a one-size fits all change, every single core would have to have it added manually. Since the Genesis analog out produces the same signal, you have to make it so each increment moving in x y would modify the video signal.

Not saying it's impossible, but just trying to help manage expectations.

**Comment by drstorm** [comment]
That's definitely beyond my current abilities. I'm a total noob when it comes to HDLs. In this PR, I only put some wires together.

**Comment by drstorm** [comment]
I realized that I did not take the H/V Blank signals from the filter. I'll amend the commit to fix that.

Looking at the code of the filter, the H/V sync and blank are delayed by 1 pixel clock cycle. I used 240p Test Suite to check for overscan and with the delay, the picture shift to the right is reduced by 1px.

By modifying the the shift register to have 4 stages, instead of 1 [here](https://github.com/jotego/jtframe/blob/master/hdl/video/jtframe_wirebw.v#L42), the picture does not shift to the right any more. Obviously this increases latency by a few cycles, but I think it's worth it and I wonder why Jotego chose to only use 1px offset.

What do you guys think?

**Comment by jotego** [comment]
It should be four indeed. Don't worry about a 4-pixel delay, that is way below anything perceptible.

**Comment by drstorm** [comment]
Thanks for the reply! I can submit a PR for `jtframe` for that. I was just wondering though if this is 4 because N=5 in the filter, so it should generally be N-1, or is it just... 4.

You can probably tell, but I don't really know how the filter works. :)

**Comment by jotego** [comment]
I already corrected in JTFRAME, thanks for pointing it out :-D

**Comment by drstorm** [comment]
lol :D

**Comment by sorgelig** [comment]
There will be shadow mask implementation for old CRT effect which should be enough to play with quality.
Anyway, this PR will be postponed till that time, then will be decided later.

> great job I would like to ask you if you could pass the function of horizontal and vertical scrolling of the game cores

it definitely won't happen in console and computer cores.

**Comment by drstorm** [comment]
In my private build I have both the shadow mask and the Old TV filter. Using them together is my preferred way of playing.

The shadow mask option does not really deal with the need for color blending on Genesis, IMO. I was thinking, perhaps this filter should the 4th state of the existing Composite Blend option. It kind of achieves the same thing via a different algorithm. Let me know what you think.

I'm suggesting that, because then there would be no additional clutter in the menu, nor would I need to use an additional status bit.

**Comment by drstorm** [comment]
Hey Sorg, just wondering if you have decided on this PR now that the shadow masks are in. Thanks.

**Comment by jotego** [comment]
I think this can be closed as the shadow masks are working quite well.

**Comment by drstorm** [comment]
I don't think that's quite the same, but then I always thought there was a slim chance to get this merged, so it's OK.

**Pull request closed without merging**
