### PR TITLE
Cleanup root folder

### PR DESCRIPTION
**Pull request by birdybro**
Inspired by suggestion from @ElectronicsArchiver

### CODE REVIEW

**Comment by sorgelig** [comment]
why you think these files should be removed?

**Comment by birdybro** [comment]
Quartus 13 is fully deprecated and unavailable from Intel and we don't use it for the project as far as I'm aware, it is used in MiST I believe still because they use a Cyclone III. Sorry if I made some mistaken assumptions.

**Comment by birdybro** [comment]
Kitrinx explained to me that you use these for quicker iterations, I'm sorry to have been presumptuous.

**Comment by sorgelig** [comment]
Q13 refers to Quartus 13.1 which is 1) supports Cyclone V 2) is NOT deprecated. exactly 13.1 was excluded from deprecation (according to Intel note) as it's the latest Cyclone III version.

Q13 version allows much faster compilation which is good for debugging.

**Pull request closed without merging**
