### PR TITLE
Update core location to match latest update script

### PR DESCRIPTION
**Pull request by patridge**
…also updated Markdown to prevent unintentional formatting

Hopefully this keeps others from hitting the same "update isn't updating my cores" issue I hit.

## Background

This was the core I started with on MiSTer back in Jan 2020. I started putting all my cores in the root /media/fat location.

Fast forward to this month. The update script is expecting things in /media/fat/_Console and I can't figure out why my root cores are so out-of-date.

### CODE REVIEW

**Comment by sorgelig** [comment]
It's usage specific path. It doesn't have to be inside _Computer path.
For example, i don't sort the cores on my SD card besides the _Arcade folder specifically for arcades.

**Comment by birdybro** [comment]
I suggest this be changed from:

```
Copy the \*.rbf to the **/media/fat/\_Console** folder of the MiSTer SD card. Put some ROMs (\*.BIN/\*.GEN/\*.MD) into the Genesis folder.
```

to:

```
Copy the `*.rbf` to the `/_Console/` folder of the MiSTer SD card. Put your ROMs (`*.BIN`, `*.GEN`, and `*.MD` supported) into the `/games/Genesis/` folder.
```

Which will appear like this in markdown:

Copy the `*.rbf` to the `/_Console/` folder of the MiSTer SD card. Put your ROMs (`*.BIN`, `*.GEN`, and `*.MD` supported) into the `/games/Genesis/` folder.

**Comment by sorgelig** [comment]
_Console part should be removed from path in readme. It's usage specific and basically up to use how he/she wants to organize it. It's not hard coded and should not confuse the user.
If user uses update script, then it will be automatically copied/updated according to script preferences.

**Comment by patridge** [comment]
Sorry, I didn't mean to add any confusion. I just went through half a day debugging why my cores weren't being updated because the update script was expecting cores to be in certain underscore directories like that by default. I'll gladly withdraw the PR if it will only cause additional user issues. I just wanted to help new users like myself avoid that pitfall.
https://github.com/MiSTer-devel/Updater_script_MiSTer/blob/master/mister_updater.sh#L102-L106

**Pull request closed without merging**
