### PR TITLE
Restore Ladder Effect and Audio Balance after update to jt12/jt89

### PR DESCRIPTION
**Pull request by birdybro**
The ladder effect code from @Kitrinx was adjusting the jt89 and jt12 balance already, so restoring the ladder effect restores this balance.

DA__ALL_MiSTer_20220326_vs_untitled_0000

### CODE REVIEW

**Comment by sorgelig** [comment]
In general it looks like rolling back some jt12 changes. While it solves one problem it may roll back some other possible fixes.

**Comment by birdybro** [comment]
That's a good point. The Super Monaco GP sound is still fixed in my build with these changes. The ladder effect also sounds identical to my ears when testing. I will look through the jt12 commit history for clues for some of these potential fixes.

**Comment by sorgelig** [comment]
while your test may not find problems, IRQ should be swapped back to correct positions.

**Comment by sorgelig** [comment]
Also, in short term it looks like fixed the problem but it will stuck to older version of jt12 and will prevent direct updates. It's better if @jotego would add ladder mode into his code instead.

**Comment by birdybro** [comment]
I agree, if the ladder mode were in the code, then it would also benefit anyone who decides to make an FM Towns core in the future. I'll close this request as it should be done in the jt12 module instead.

**Comment by birdybro** [comment]
I'm going to look at this again, but don't let that stop anyone else from looking into it. I swapped back the IRQ. I would convert this to a draft, but I don't have write access to the repo, so couldn't.

**Comment by birdybro** [comment]
@jotego - Does this modify any of your previous bugfixes in any way?

**Comment by birdybro** [comment]
https://github.com/jotego/jt12/issues/63 - created issue, referencing here

**Comment by sorgelig** [comment]
@birdybro it seems original jt12 repo will delay with ladder mod. Please make PR with your ladder addon for latest jt12 so we will move forward.

**Comment by birdybro** [comment]
Sure thing, I'll make the adjustments and submit a PR. :)

**Comment by jotego** [comment]
Sorry about the delay. Please go ahead and I'll notify you when I have it ready.

**Comment by birdybro** [comment]
It's merged in Genesis now.

**Pull request closed without merging**
