### PR TITLE
Fixed reloading of the tone register to match hardware more closely. …

### PR DESCRIPTION
**Pull request by Enforcer831**
… This fixes an off by one error causing the pitch of the tone to be wrong.

Fixed noise counters to fix the noise frequency being doubled.

Fixed not updating noise register on data byte.

### CODE REVIEW

**Comment by sorgelig** [comment]
Thanks!
Which games it affects?

**Comment by Enforcer831** [comment]
It actually affects anything that used the PSG, which most games did to varying degrees.  I am still working on figuring out the proper mix levels.  This fix should be applied to the SMS core as well.  If you'd like I can do the changes and create a pull request.

**Comment by sorgelig** [comment]
Still would be good to name some games where can clearly hear the difference between before and after.

Yeah, you are free to make PR for SMS too.

**Comment by Enforcer831** [comment]
The place I personally noticed it the most was in Sonic 3 Angel Island for the tone pitch.  Especially at the Riff at the end of the phrase of the song.  It was fairly noticeable in almost all of the songs in sonic.  Verified the pitches and noise generation with the 240p test suite as well.

**Comment by jotego** [comment]
There are a lot of changes and I do not see enough documentation supporting the changes. There are reports about the count reset occuring at zero and at one on the internet. The sampe applies to ctrl3 register. So, we need a die shot or someone making a test on real hardware. In the meantime, I wouldn't change the value.
Deleting **v** in the noise module is just a comestic change? You have introduced another 11-bit comparator in the if clause. LUTs are more valuable than flip flops, so **v**  register was saving logic. I wouldn't make that change.

**Comment by Enforcer831** [comment]
The v flip flop for some reason did not result in the divide by two that is in the spec sheet. Also the noise channel has to take into account the 0 input from tone 2 behaving the same as a 1 for proper frequency output. In the real hardware, the outputs of all the channels are just 0-1 and tone2s output is fed directly into noise. That would reduce the required resources but would have mean a major tear up of the design. The updating the noise channel on a data byte was discovered many years ago and documented on SMS power. You can see the effects of this on the 240P rom test. As well as the divide by two not working. On the tone register, the original does an async reload of the register when the count hits zero. The next decrement would happen on the next clock cycle. That’s why 0 on a discreet part acts like a $400 when doing the frequency calculation by hand. As implemented, you inject an extra clock cycle and shift all the pitches.  All pitches were verified with a scope and spectrum analyzer and a/b tested with real genesis creating the same graphs. Noise was tested with by a/b testing and by generating a spectrograph if all the fundamental frequencies and comparing against a real genesis.

**Comment by jotego** [comment]
@Enforcer831 thank for your detailed explanation. I have added your changes to the main repository (the MiSTer Genesis one is only a local copy). Here is the [commit](https://github.com/jotego/jt89/commit/13da1edcd56b15f3fe01d075acdc7ef48e879d2a).

**Pull request merged**
