### PR TITLE
Audio Filters for Model 1 and Model 2 Genesis

### PR DESCRIPTION
**Pull request by ghogan42**
Implements 6db and 12db/octave audio filters to match Model 1 and Model 2 Genesis.
Adds OSD options to select filter: Model1/Model2/Minimal/No Filter

### CODE REVIEW

**Comment by ghogan42** [comment]
Somehow there were a couple of simple formatting problems in the files (tabs not lining up...).  They look fine in Quartus...
I can fix these as well as anything else that needs to be fixed and make another pull request if necessary. No big deal.
See the Genesis thread on the forum for measurements + filter sims.

**Comment by jotego** [comment]
JT12 produces an output called **sample** to indicate the sampling rate. I see that your filter does not have a clock enable signal, and you use an input called **div** to adjust the sampling rate. I think it would be safer if you modified your code to use the **sample** signal from JT12. That way you can be sure you have the right sampling rate. Plus, we save some logic.

**Comment by ghogan42** [comment]
Thanks jotego, I wrote it the way I did because didn't know what rate I wanted to sample the audio at. I saw in signaltap that the audio stream changed more often after mixing than the FM sample rate. So I thought I would just sample it faster: 106khz instead of 53khz.  I can rewrite it to use **sample** if that is better.

**Comment by jotego** [comment]
I think the merge is broken. At least it is not doing what is intended.

The FM sampling rate is slower than the PSG one. If you look inside the genmix module you will see a lot of interpolation and decimation filters to match the two sample rates and then make the output sample rate the same as the system rate. You can follow the code and see the various “sample” signal in the form of clock enablers in it.

I think your filter, as it is, may not be filtering at the intended cut off frequency because of all this data resampling.

Filter coefficients at the master clock rate will be too many. So it is better to do it at the front end of the mixing when data rate is low. You may consider two filters, one for the PSG and one for the FM as they have different sample rates.

**Comment by ghogan42** [comment]
First: I'm changing the code to do it the way you suggest. If sorgelig wants it that way too I can resubmit it.

But that is why I used the divider from the original clock.  The filter coefficients were computed and verified for a 106528hz sampling rate.  Then the filter samples the audio stream at this rate. It shouldn't matter if the PSG and FM were generated at different rates.

It would be like if you were recording the genesis audio with an external device. If you sample at 106khz then it shouldn't matter (much...) if the audio stream was originally generated at 53khz or 20khz or anything else as long as you sampled the audio at a high enough rate to avoid aliasing. Or am I wrong?

But I think it was correct. I can measure the filter again for PSG and FM and show you the measured response. Maybe there is an error.

**Comment by sorgelig** [comment]
I didn't study the code but in general I agree with ghogan42 to have independent external filter which won't be bound to specific sample rate of FM/PSG. It's more universal and can be re-used in other cores.
I just would like to ask to re-calculate it to 96KHz. 96KHz is a base sample rate for i2s and TOSLink output. 
So, this will be even more compatible with MiSTer's audio output.

**Comment by ghogan42** [comment]
I didn't have PSG only samples already recorded. But here are samples of the measured response curve of the filters from the test build I made yesterday.
mode1_1_result
mode1_2_fm_result

**Comment by sorgelig** [comment]
Is this answer to me? 
Filters working at 96KHz will absorb the possible small distortions due to difference of sampling rate in input and will provide cleaned 96KHz audio which will match the sampling rate MiSTer's output.

**Comment by jotego** [comment]
@ghogan42 how did you obtain those plots? How do you explain the measured response turning up at high frequencies?

When you sample a signal you need to limit its bandwidth, otherwise you get aliasing. In the analog world you use low pass filters to do that. If you sample at 100kHz, you need to limit the input BW to 50kHz. And if you sample at 30kHz, you need to limit it at 15kHz. So you need different filters depending on your sampling rate.

It is exactly the same in the digital domain. When you have a signal whose rate is 50kHz and you just assume that its rate is now 100kHz and duplicate each sample, you are actually introducing a full copy of that signal spectrum centered at 50kHz! You can try this in Matlab/Octave, it is actually quite interesting to see it.

Now, these old systems already have sound that is a bit broken. Like the voices in Altered Beast that have the wrong sampling rate at playback -and sound terrible. So you can add more distortion to it and maybe even like it. But you are actually distorting the signal. I would reverse this merge if I was in charge.

**Comment by sorgelig** [comment]
This is optional filtering. 
Besides the theory i clearly hear the difference. Higher frequency will be filtered at i2s/spdif modules filtering.

**Comment by sorgelig** [comment]
@jotego, 
MiSTer uses fixed 96/48KHz sampling rates for i2s/SPDIF, thus such difference between sampling rates was there already.

**Comment by ghogan42** [comment]
@jotego The plot for the simulation is from Octave (free Matlab implementation). It is the computed filter transfer function. The plot for the "Measured" filter is the difference between the unfiltered/filtered spectrum for a particular audio sample from two recordings.

The *simulated filter* starts to level out above 10khz because the filter was designed to match the measured Genesis audio samples I was given. It's important to understand the the **only** goal of these filters was to match the response under 20khz or so.  I thought the "turn up" at the top end was a measurement error from the low signal at those frequencies and the way I made the spectrum.

**No** effort was spent trying to properly low-pass the audio to avoid aliasing. I thought that this was done in mister later on in another module before going out analog/spdif/hdmi and that I didn't need to do it myself. I mistakenly thought that I could sample and then a later low-pass would take care of things. But I read a little more (I know next to nothing about this topic) and I see that you are correct.  

I think I can fix the filter by separately filtering the PSG and FM streams before mixing and sampling properly.  Either using the **sample** signal like you said or possibly just by using the correct divider.

What I don't understand is where in MiSTer is sample rate conversion done properly? For example, after mixing, what is the sample rate of the Genesis core audio?  How does this end up at 96khz (or 48khz?) in the end without aliasing?

**Comment by sorgelig** [comment]
There is no sample rate conversion as framework generally doesn't know original sample rate of the core. So it simply pick the samples at the fixed rate 48 or 96 to feed into i2s/spdif. That's why for better quality it's better to use 96KHz as a base for filter.

**Pull request merged**
